version: '3'
services:
  nginx:
    depends_on:
      - Backend
      - Frontend
    restart: always
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ../Backend:/app/Backend
  frontend:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - /app/Frontend/node_modules
      - ../Frontend:/app/Frontend
